language: node_js
node_js:
- '6'
addons:
  sonarqube: true
env:
  global:
    secure: Ga1aWCn25INlwzkVpGBDbAIjOyraxss2wygQfxcVkTitzTMPMBFhy4T7Trkhf8Bw2Qn7Tu45hza9bpG2niu1e+HOqdirWtAbalIDFG7fXPuNrPBn93C8bcJBdwH3Kp7wb4sbCO2SNNRb9uZ8hFXIt/Af9HayMl9bqeHCvvO3FoabMc3C4wnO2o6j6LrS0CEYvT+PsfMFXJpcb00Gyruwh3H7/e/QuhojciHbQ4otqEjhIodWiYIgQEwCdn3CcGN15fw5wkGyKxkOqX30bMFzyOcnOx6kY6DzV83GT8rAyeOlxpedhc+Pj92pUpdPe7m27HU5k3w+ZEdEvLSzLIR0RIwFP9cdFuKpgi0H9WSclbXcswauy8L7dWbARrbcE7yzK1/hG9XaHnTQOWgDonKctHkIqcB1Rvo9tEsLE3rta6W1ncE87d5jNgXMAl1EtMvdXuaJBPvc6GAnQwo0rnYxdEENji3R5NMm644GsxxSO70B68Ucvb3Adge7EpoRvqUqPko3dipbxL+7zHXZGDFFMyCb4dwTcj/ptjhasrY5Z73Csw/CoUZbL2pi4cwhKmsa1zrRLS97M85GxVIy0H6UUUvTs/v34mbLbEwcAsdrBV2DG9t9ZVTpo+zEKarbTHob1nPLHW2c2tm8QEwGQBEg9oNYdiWEm6lHY47xsaJjDmA=
script:
- sonar-scanner -Dsonar.login=$CYLLAGE_TOKEN